(function() {var implementors = {};
implementors["wasmtime"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"wasmtime/struct.Config.html\" title=\"struct wasmtime::Config\">Config</a>",synthetic:false,types:["wasmtime::runtime::Config"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"wasmtime/struct.Engine.html\" title=\"struct wasmtime::Engine\">Engine</a>",synthetic:false,types:["wasmtime::runtime::Engine"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"wasmtime/wasm/struct.wasm_val_t.html\" title=\"struct wasmtime::wasm::wasm_val_t\">wasm_val_t</a>",synthetic:false,types:["wasmtime::wasm::wasm_val_t"]},];
implementors["wasmtime_environ"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"wasmtime_environ/struct.Tunables.html\" title=\"struct wasmtime_environ::Tunables\">Tunables</a>",synthetic:false,types:["wasmtime_environ::tunables::Tunables"]},];
implementors["wasmtime_jit"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"wasmtime_jit/struct.Features.html\" title=\"struct wasmtime_jit::Features\">Features</a>",synthetic:false,types:["wasmtime_jit::context::Features"]},];
implementors["wasmtime_runtime"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"wasmtime_runtime/struct.VMSharedSignatureIndex.html\" title=\"struct wasmtime_runtime::VMSharedSignatureIndex\">VMSharedSignatureIndex</a>",synthetic:false,types:["wasmtime_runtime::vmcontext::VMSharedSignatureIndex"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"wasmtime_runtime/struct.VMCallerCheckedAnyfunc.html\" title=\"struct wasmtime_runtime::VMCallerCheckedAnyfunc\">VMCallerCheckedAnyfunc</a>",synthetic:false,types:["wasmtime_runtime::vmcontext::VMCallerCheckedAnyfunc"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()